import React from 'react';
import { motion } from 'framer-motion';

const TermsOfService = () => {
    return (
        <div className="pt-32 pb-20 px-6 max-w-4xl mx-auto">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
            >
                <h1 className="text-4xl font-display font-bold text-white mb-8">
                    Terms of <span className="gradient-text">Service</span>
                </h1>
                
                <div className="prose prose-invert max-w-none space-y-6 text-textMuted">
                    <p><strong>Effective Date:</strong> January 1, 2026</p>
                    
                    <h2 className="text-xl font-semibold text-white">1. Acceptance of Terms</h2>
                    <p>
                        By downloading, accessing, or using the UBIRT.AI application or website, you agree to be bound 
                        by these Terms of Service. If you do not agree to these terms, please do not use our services.
                    </p>

                    <h2 className="text-xl font-semibold text-white">2. Use License</h2>
                    <p>
                        Permission is granted to temporarily download one copy of the materials (information or software) 
                        on UBIRT.AI's website for personal, non-commercial transitory viewing only. This is the grant 
                        of a license, not a transfer of title, and under this license you may not:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Modify or copy the materials;</li>
                        <li>Use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
                        <li>Attempt to decompile or reverse engineer any software contained on UBIRT.AI's website;</li>
                        <li>Remove any copyright or other proprietary notations from the materials; or</li>
                        <li>Transfer the materials to another person or "mirror" the materials on any other server.</li>
                    </ul>

                    <h2 className="text-xl font-semibold text-white">3. User Conduct</h2>
                    <p>
                        You agree to use the application strictly for lawful purposes. You may not use the service 
                        to generate, distribute, or promote any unauthorized or harmful content.
                    </p>

                    <h2 className="text-xl font-semibold text-white">4. Intellectual Property</h2>
                    <p>
                        All content generated by UBIRT.AI, including the AI reels, graphics, and structure, remains 
                        the intellectual property of UBIRT.AI unless otherwise noted.
                    </p>

                    <h2 className="text-xl font-semibold text-white">5. Disclaimer</h2>
                    <p>
                        The materials on UBIRT.AI's website are provided on an 'as is' basis. UBIRT.AI makes no 
                        warranties, expressed or implied, and hereby disclaims and negates all other warranties 
                        including, without limitation, implied warranties or conditions of merchantability, 
                        fitness for a particular purpose, or non-infringement of intellectual property or 
                        other violation of rights.
                    </p>

                    <h2 className="text-xl font-semibold text-white">6. Limitation of Liability</h2>
                    <p>
                        In no event shall UBIRT.AI or its suppliers be liable for any damages (including, without 
                        limitation, damages for loss of data or profit, or due to business interruption) arising 
                        out of the use or inability to use the materials on UBIRT.AI's website, even if 
                        UBIRT.AI or a UBIRT.AI authorized representative has been notified orally or in 
                        writing of the possibility of such damage.
                    </p>

                    <h2 className="text-xl font-semibold text-white">7. Governing Law</h2>
                    <p>
                        These terms and conditions are governed by and construed in accordance with the laws of 
                        the jurisdiction in which UBIRT.AI operates and you irrevocably submit to the exclusive 
                        jurisdiction of the courts in that State or location.
                    </p>
                </div>
            </motion.div>
        </div>
    );
};

export default TermsOfService;
