import React from 'react'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import CommunityProof from './components/CommunityProof'
import Features from './components/Features'
import SocialLinks from './components/SocialLinks'
import Footer from './components/Footer'
import BackToTop from './components/BackToTop'
import LegalPopup from './components/LegalPopup'

function App() {
  const [activePopup, setActivePopup] = React.useState(null);

  const privacyContent = (
    <>
      <p><strong>Effective Date:</strong> January 1, 2026</p>
      <h4 className="text-white font-semibold text-lg mt-4">1. Information We Collect</h4>
      <p>We collect information you provide directly to us when you create an account, such as your name, email address, and viewing preferences. We also automatically collect data regarding your interaction with UBIRT.AI, including device information, IP address, and usage statistics.</p>

      <h4 className="text-white font-semibold text-lg mt-4">2. How We Use Your Information</h4>
      <p>Your information is used to personalize your experience, tailor the AI-generated motivational reels to your specific goals (Motivation, Health, Sports), and improve the overall functionality of the application.</p>

      <h4 className="text-white font-semibold text-lg mt-4">3. Data Security</h4>
      <p>We implement standard security measures to protect your personal information. However, no method of transmission over the internet or electronic storage is 100% secure.</p>

      <h4 className="text-white font-semibold text-lg mt-4">4. Contact Us</h4>
      <p>If you have questions regarding this Privacy Policy, please contact us at <a href="mailto:info@ubirtai.site" className="text-success hover:underline">info@ubirtai.site</a>.</p>
    </>
  );

  const termsContent = (
    <>
      <p><strong>Effective Date:</strong> January 1, 2026</p>
      <h4 className="text-white font-semibold text-lg mt-4">1. Acceptance of Terms</h4>
      <p>By downloading, accessing, or using the UBIRT.AI application, you agree to be bound by these Terms of Service.</p>

      <h4 className="text-white font-semibold text-lg mt-4">2. User Conduct</h4>
      <p>You agree to use the application strictly for lawful purposes. You may not use the service to generate, distribute, or promote any unauthorized or harmful content.</p>

      <h4 className="text-white font-semibold text-lg mt-4">3. Intellectual Property</h4>
      <p>All content generated by UBIRT.AI, including the AI reels, graphics, and structure, remains the intellectual property of UBIRT.AI unless otherwise noted.</p>

      <h4 className="text-white font-semibold text-lg mt-4">4. Limitation of Liability</h4>
      <p>UBIRT.AI is provided "as is". We are not liable for any direct, indirect, or incidental damages resulting from your use of the app or its content recommendations.</p>
    </>
  );

  return (
    <div className="min-h-screen bg-background text-textMain relative selection:bg-success/30 selection:text-white">
      {/* Global Background Noise Effect */}
      <div
        className="fixed inset-0 z-50 pointer-events-none opacity-[0.015] mix-blend-overlay"
        style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")` }}
      ></div>

      <Navbar />

      <main>
        <Hero />
        <CommunityProof />
        <Features />

        {/* Transition Divider */}
        <div className="w-full h-px bg-gradient-to-r from-transparent via-white/10 to-transparent my-12"></div>

        <SocialLinks />
      </main>

      <Footer onOpenLegal={(type) => setActivePopup(type)} />
      <BackToTop />

      <LegalPopup
        isOpen={activePopup === 'privacy'}
        onClose={() => setActivePopup(null)}
        title="Privacy Policy"
        content={privacyContent}
      />
      <LegalPopup
        isOpen={activePopup === 'terms'}
        onClose={() => setActivePopup(null)}
        title="Terms of Service"
        content={termsContent}
      />
    </div>
  )
}

export default App
